package edu.eci.cosw.flightsex.persistence.model;
// Generated Aug 12, 2015 11:13:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pasajeros generated by hbm2java
 */
@Entity
@Table(name="PASAJEROS"
    ,catalog="bdprueba"
)
public class Pasajero implements java.io.Serializable {


     private int identifiacion;
     private String nombre;
     private int anyoNacimiento;

    public Pasajero() {
    }

    public Pasajero(int identifiacion, String nombre, int anyoNacimiento) {
       this.identifiacion = identifiacion;       
       this.nombre = nombre;
       this.anyoNacimiento = anyoNacimiento;
    }
   
     @Id 

    
    @Column(name="IDENTIFIACION", unique=true, nullable=false)
    public int getIdentifiacion() {
        return this.identifiacion;
    }
    
    public void setIdentifiacion(int identifiacion) {
        this.identifiacion = identifiacion;
    }

        
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ANYO_NACIMIENTO", nullable=false)
    public int getAnyoNacimiento() {
        return this.anyoNacimiento;
    }
    
    public void setAnyoNacimiento(int anyoNacimiento) {
        this.anyoNacimiento = anyoNacimiento;
    }




}


