package edu.eci.cosw.flightsex.persistence.model;
// Generated Aug 12, 2015 11:13:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pilotos generated by hbm2java
 */
@Entity
@Table(name="PILOTOS"
    ,catalog="bdprueba"
)
public class Piloto  implements java.io.Serializable {


     private int idpiloto;
     private String nombre;
     private int anyoNacimiento;     

    public Piloto() {
    }

	
    public Piloto(int idpiloto, String nombre, int anyoNacimiento) {
        this.idpiloto = idpiloto;
        this.nombre = nombre;
        this.anyoNacimiento = anyoNacimiento;
    }
   
    @Id 
    @Column(name="IDPILOTO", unique=true, nullable=false)
    public int getIdpiloto() {
        return this.idpiloto;
    }
    
    public void setIdpiloto(int idpiloto) {
        this.idpiloto = idpiloto;
    }

    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ANYO_NACIMIENTO", nullable=false)
    public int getAnyoNacimiento() {
        return this.anyoNacimiento;
    }
    
    public void setAnyoNacimiento(int anyoNacimiento) {
        this.anyoNacimiento = anyoNacimiento;
    }





}


