package edu.eci.cosw.flightsex.persistence.model;
// Generated Aug 12, 2015 11:13:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelos generated by hbm2java
 */
@Entity
@Table(name="VUELOS")
public class Vuelo implements java.io.Serializable {


     private String idvuelo;
     private Aeronave aeronaves;
     private Piloto pilotos;
     private Date fecha;
     private int duracion;
     private Set<Pasajero> pasajeros = new HashSet<>(0);

    public Vuelo() {
    }

	
    public Vuelo(String idvuelo,Aeronave aeronaves, Piloto pilotos, Date fecha, int duracion) {
        this.idvuelo = idvuelo;
        this.aeronaves = aeronaves;
        this.pilotos = pilotos;
        this.fecha = fecha;
        this.duracion = duracion;
    }
    public Vuelo(String idvuelo,Aeronave aeronaves, Piloto pilotos, Date fecha, int duracion, Set pasajeroses) {
       this.idvuelo = idvuelo;
       this.aeronaves = aeronaves;
       this.pilotos = pilotos;
       this.fecha = fecha;
       this.duracion = duracion;
       this.pasajeros = pasajeroses;
    }
   
    @Id 
    @Column(name="IDVUELO", unique=true, nullable=false, length=10)
    public String getIdvuelo() {
        return this.idvuelo;
    }
    
    public void setIdvuelo(String idvuelo) {
        this.idvuelo = idvuelo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AERONAVES_IDAERONAVE", nullable=false)
    public Aeronave getAeronave() {
        return this.aeronaves;
    }
    
    public void setAeronave(Aeronave aeronaves) {
        this.aeronaves = aeronaves;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PILOTOS_IDPILOTO", nullable=false)
    public Piloto getPiloto() {
        return this.pilotos;
    }
    
    public void setPiloto(Piloto pilotos) {
        this.pilotos = pilotos;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHA", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="DURACION", nullable=false)
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name = "VUELOS_IDVUELO")
    public Set<Pasajero> getPasajeros() {
        return this.pasajeros;
    }
    
    public void setPasajeros(Set<Pasajero> pasajeros) {
        this.pasajeros = pasajeros;
    }




}


